name: Skompiluj dokumenty

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Typst
        uses: typst-community/setup-typst@v4
      - name: Compile documents
        run: |
          sudo chmod +x ./build.sh
          ./build.sh
      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: |
            kti.pdf
            kaims.pdf
            default.pdf
  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download PDFs
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: docs
      # Release for tag pushes
      - name: Create version release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          make_latest: true
          draft: false
          generate_release_notes: true
          files: docs/*

      # Draft release for manual dispatch
      - name: Create draft release (manual)
        if: github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v2
        with:
          name: Draft ${{ github.sha }}
          tag_name: manual-${{ github.sha }}
          target_commitish: ${{ github.sha }}
          make_latest: false
          draft: true
          generate_release_notes: true
          files: docs/*